spring.application.name=restaurant-api-gateway

server.port=8080

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway Discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoints.web.exposure.include=*

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://RESTAURANT-AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Menu Service
spring.cloud.gateway.server.webflux.routes[1].id=menu-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://RESTAURANT-MENU-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/menu/**

# Order Service
spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://RESTAURANT-ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orders/**

# Billing Service
spring.cloud.gateway.server.webflux.routes[3].id=billing-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://RESTAURANT-BILLING-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/billing/**